name: CUC-Auto-Clock CI

on:
  schedule:
    # 由于这周开学，暂时不在周末运行
    - cron: "0 8 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          apt update
          apt install python
          python main.py
