name: CUC-Auto-Clock CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "21 7 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the Python Script for LJY
        continue-on-error: true
        id: ljy
        env:
          ljy_userid: ${{ secrets.LJY_ID }}
          ljy_stuno: ${{ secrets.LJY_STUDENT_NUMBER }}
          ljy_passwd: ${{ secrets.LJY_PASSWORD }}
        run: |
          pip install -r requirements.txt
          cp main.py ljy/
          python ljy/main.py -s "$ljy_stuno" -p "$ljy_passwd" --userid "$ljy_userid"
      - name: Run the Python Script for CWX
        continue-on-error: true
        id: cwx
        env:
          cwx_userid: ${{ secrets.CWX_ID }}
          cwx_stuno: ${{ secrets.CWX_USER }}
          cwx_passwd: ${{ secrets.CWX_PASSWD }}
        run: |
          cp main.py cwx/
          python cwx/main.py -s "$cwx_stuno" -p "$cwx_passwd" --userid "$cwx_userid"
      - name: Run the Python Script for LZQ
        continue-on-error: true
        id: lzq
        env:
          lzq_userid: ${{ secrets.LZQ_USER }}
          lzq_stuno: ${{ secrets.LZQ_ID }}
          lzq_passwd: ${{ secrets.LZQ_PASSWD }}
        run: |
          cp main.py lzq/
          python lzq/main.py -s "$lzq_stuno" -p "$lzq_passwd" --userid "$lzq_userid"
      - name: Run the Python Script for YML
        continue-on-error: true
        id: yml
        env:
          yml_userid: $ {{ secrets.YML_ID }}
          yml_stuno: ${{ secrets.YML_STUDENT_NUMBER }}
          yml_passwd_p1: ${{ secrets.YML_PASSWORD1 }}
          yml_passwd_p2: ${{ secrets.YML_PASSWORD2 }}
        run: |
          cp main.py yml/
          python yml/main.py -s "$yml_stuno" -p "${yml_passwd_p1}%${yml_passwd_p2}" --userid "$yml_userid"
  restart_when_failed:
    runs-on: ubuntu-latest
    if: failure()
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Send an Email if failed
      uses: dawidd6/action-send-mail@master
      with:
        serveraddress: smtp.qq.com
        serverport: 465
        username: ${{ secrets.MAIL_ACCOUNT }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'GitHub Action Test User'
        body: 'Test Email'
        to: lyujiuyang@cuc.edu.cn
        from: GitHub Actions
        content_type: text/html
